/**
 * 官方房间美术（ADR 0006）：screeps/renderer 的 metadata/images 下全部 117 个 SVG（ISC），
 * 原样放在 `web/public/official-art/`，随构建产物发布并进入 PWA 预缓存；LICENSE.txt 与来源 commit
 * （SOURCE.txt）在同一目录。PNG 纹理不打包，由用到它的票按需加载。
 *
 * Scene 的 image 图元用 {@link officialArtUrl} 得到的同源 URL 引用贴图；适配层按 URL 栅格化一次并缓存。
 */

/** 官方 SVG 的文件名（不含扩展名）；art-assets.test.ts 校验与目录内容一致 */
export const OFFICIAL_SVG_NAMES = [
  "berserk",
  "bodyPartBar",
  "commander-lvl0",
  "commander-lvl1",
  "commander-lvl2",
  "commander-lvl3",
  "commander-lvl4",
  "commander",
  "constructedWall",
  "controller-level",
  "controller",
  "cover",
  "creep-npc",
  "defend",
  "demolish",
  "deposit-biomass-fill",
  "deposit-biomass",
  "deposit-metal-fill",
  "deposit-metal",
  "deposit-mist-fill",
  "deposit-mist",
  "deposit-silicon-fill",
  "deposit-silicon",
  "disable",
  "disrupt-source",
  "disrupt-spawn",
  "disrupt-terminal",
  "disrupt-tower",
  "drain-extension",
  "encourage",
  "executor-lvl0",
  "executor-lvl1",
  "executor-lvl2",
  "executor-lvl3",
  "executor-lvl4",
  "executor",
  "exhaust",
  "exit-bottom",
  "exit-left",
  "exit-right",
  "exit-top",
  "extension-border100",
  "extension-border200",
  "extension-border50",
  "extension",
  "extractor",
  "factory-border",
  "factory-highlight",
  "factory-lvl0",
  "factory-lvl1",
  "factory-lvl2",
  "factory-lvl3",
  "factory-lvl4",
  "factory-lvl5",
  "factory",
  "flag-secondary",
  "flag",
  "fortify",
  "generate-ops",
  "harvest-energy",
  "harvest-mineral",
  "invaderCore",
  "kill",
  "lab-highlight",
  "lab-mineral",
  "lab",
  "link-border",
  "link-energy",
  "link",
  "mass-repair",
  "nuker-border",
  "nuker",
  "nuke",
  "operate-controller",
  "operate-extension",
  "operate-lab",
  "operate-observer",
  "operate-power",
  "operate-spawn",
  "operate-storage",
  "operate-terminal",
  "operate-tower",
  "operator-lvl0",
  "operator-lvl1",
  "operator-lvl2",
  "operator-lvl3",
  "operator-lvl4",
  "operator",
  "powerBank",
  "punch",
  "rampart",
  "rectangle",
  "reflect",
  "regen-mineral",
  "regen-source",
  "reinforce",
  "remote-transfer",
  "renew",
  "ruin",
  "shield",
  "sight",
  "snipe",
  "storage-border",
  "storage",
  "summon",
  "tbd",
  "terminal-arrows",
  "terminal-border",
  "terminal-highlight",
  "terminal",
  "tombstone-border",
  "tombstone-resource",
  "tombstone",
  "tough",
  "tower-base",
  "tower-rotatable-npc",
  "tower-rotatable",
] as const;

export type OfficialSvgName = (typeof OFFICIAL_SVG_NAMES)[number];

/** 官方美术在站点上的目录（相对站点根） */
export const OFFICIAL_ART_DIR = "official-art";

/** 官方 SVG 的同源 URL，例如 `/official-art/storage.svg` */
export function officialArtUrl(name: OfficialSvgName): string {
  return `${import.meta.env.BASE_URL}${OFFICIAL_ART_DIR}/${name}.svg`;
}
